Classification
Objective:  
The objective of this assessment is to evaluate your understanding and ability to apply
supervised learning techniques to a real-world dataset.  
Dataset:  
Use the breast cancer dataset available in the sklearn library.  
Key components to be fulfilled:  
Loading and Preprocessing (2 marks):
● Load the breast cancer dataset from sklearn.  
● Preprocess the data to handle any missing values and perform necessary feature
scaling.  
● Explain the preprocessing steps you performed and justify why they are
necessary for this dataset.  
Classification Algorithm Implementation (5 marks):
Implement the following five classification algorithms:  
1. Logistic Regression  
2. Decision Tree Classifier  
3. Random Forest Classifier
4. Support Vector Machine (SVM)  
5. k-Nearest Neighbors (k-NN)  
For each algorithm, provide a brief description of how it works and why it might be
suitable for this dataset.  
Model Comparison (2 marks):
● Compare the performance of the five classification algorithms.  
● Which algorithm performed the best and which one performed the worst?  
Timely Submission (1 mark)  
● Submission Guidelines: Provide your code in a Jupyter Notebook format and
submit the GitHub link here. Ensure your explanations and answers are clear and
concise.  
Total Score: 10

DATASET - (breast cancer dataset)

In [ ]:
from sklearn.datasets import load_breast_cancer
import pandas as pd

breast_cancer_data = load_breast_cancer(as_frame=True)
housing_df = breast_cancer_data.data
housing_df['target'] = breast_cancer_data.target
print(housing_df)

df = housing_df

print("load_breast_cancer dataset successfully configured from existing 'housing_df'.")
print(df)

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mea

Loading and Preprocessing (2 marks):

● Load the breast cancer dataset from sklearn.

In [ ]:
from sklearn.datasets import load_breast_cancer
import pandas as pd

breast_cancer_data = load_breast_cancer(as_frame=True)
housing_df = breast_cancer_data.data
housing_df['target'] = breast_cancer_data.target
print(housing_df)

df = housing_df

print("load_breast_cancer dataset successfully configured from existing 'housing_df'.")
print(df)
df.info()

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mea

● Preprocess the data to handle any missing values and perform necessary feature scaling.

In [2]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

breast_cancer_data = load_breast_cancer(as_frame=True)
housing_df = breast_cancer_data.data
housing_df['target'] = breast_cancer_data.target

df = housing_df

if 'target' in df.columns:
    X = df.drop('target', axis=1)
    y = df['target']
else:
    print("Warning: 'target' column not found in housing_df. Please check your data.")
    X = df.iloc[:, :-1]
    y = df.iloc[:, -1]

print("Features (X) and target (y) separated.")
print(f"X shape: {X.shape}, y shape: {y.shape}")

numerical_features = X.columns.tolist()

categorical_features = []

numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[

])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),

    ],
    remainder='passthrough'
)

X_processed = preprocessor.fit_transform(X)

df_processed = pd.DataFrame(X_processed, columns=numerical_features)

print("\nOriginal Data Set:")
print(X)
print("-" * 30)
print("\nProcessed features (missing values handled, numerical features scaled, head of data):")
print(df_processed)

Features (X) and target (y) separated.
X shape: (569, 30), y shape: (569,)

Original Data Set:
     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92 

● Explain the preprocessing steps you performed and justify why they are necessary for this dataset.

In [ ]:
print("--- Explanation of Preprocessing Steps ---")

print("\n1. Handling Missing Values:")
print("   In the load_breast_cancer, as verified by `df.info()` output from earlier cells, there are no missing values.")
print("   However, a robust preprocessing pipeline (implemented in the previous cell, `w2sZFIIG66MF`) includes `SimpleImputer(strategy='median')`")
print("   to address missing numerical values if they were present. This step is crucial in general machine learning workflows because many models cannot")
print("   handle NaN (Not a Number) values and would raise errors. Imputation ensures completeness of data for training.")

print("\n2. Feature Scaling (Standardization):")
print("   All numerical features in the dataset were standardized using `StandardScaler` (also in `w2sZFIIG66MF`).")
print("   Standardization transforms features to have a mean of 0 and a standard deviation of 1.")
print("   This is necessary because features like 'MedInc' (median income) and 'Population' can have very different scales.")
print("   Algorithms such as Linear Regression, SVR, and even tree-based methods can benefit from scaling.")
print("   For distance-based algorithms (like SVR), features on a larger scale might dominate the distance calculation.")
print("   For gradient-descent-based algorithms (like Linear Regression optimization), scaling can lead to faster convergence.")
print("   Even for tree-based models, while not strictly required, scaled features can sometimes lead to more stable splits and improved performance, especially when regularization is involved or when combined with other models.")

print("\n3. Conversion to Pandas DataFrame:")
print("   Initially, the dataset was loaded from `sklearn` and converted into a pandas DataFrame (`housing_df`, then `df`) in earlier steps.")
print("   This conversion makes data manipulation, inspection, and understanding much easier due to pandas' rich functionalities.")

print("\nJustification for Necessity:")
print("   These preprocessing steps are fundamental to prepare the data for machine learning models.")
print("   They prevent issues like models failing due to missing data, ensure features contribute equally to the model's learning process,")
print("   and often lead to better model performance and faster training times.")

--- Explanation of Preprocessing Steps ---

1. Handling Missing Values:
   In the load_breast_cancer, as verified by `df.info()` output from earlier cells, there are no missing values.
   However, a robust preprocessing pipeline (implemented in the previous cell, `w2sZFIIG66MF`) includes `SimpleImputer(strategy='median')`
   to address missing numerical values if they were present. This step is crucial in general machine learning workflows because many models cannot
   handle NaN (Not a Number) values and would raise errors. Imputation ensures completeness of data for training.

2. Feature Scaling (Standardization):
   All numerical features in the dataset were standardized using `StandardScaler` (also in `w2sZFIIG66MF`).
   Standardization transforms features to have a mean of 0 and a standard deviation of 1.
   This is necessary because features like 'MedInc' (median income) and 'Population' can have very different scales.
   Algorithms such as Linear Regression, SVR, and even tree-b

Classification Algorithm Implementation (5 marks): Implement the following five classification algorithms:

Logistic Regression

Decision Tree Classifier

Random Forest Classifier

Support Vector Machine (SVM)

k-Nearest Neighbors (k-NN)

Logistic Regression

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

print("\n--- Logistic Regression ---")
print("Logistic Regression is a linear model used for binary classification. It models the probability that a given input belongs to a certain class by applying a logistic (sigmoid) function to a linear combination of the features. The output is a probability, which is then thresholded to make a class prediction. It's suitable for this dataset because breast cancer classification is a binary outcome (malignant or benign), and the relationships between features and the target can often be well-approximated linearly in a transformed space, especially after scaling, which it benefits from.")

model_lr = LogisticRegression(random_state=42, solver='liblinear')
model_lr.fit(X_train, y_train)

print("\nLogistic Regression model training complete.")

y_pred_lr = model_lr.predict(X_test)

accuracy_lr = accuracy_score(y_test, y_pred_lr);
report_lr = classification_report(y_test, y_pred_lr)

print(f"\nModel Evaluation on Test Data (Logistic Regression):")
print(f"Accuracy: {accuracy_lr:.4f}")
print("Classification Report:")
print(report_lr)


Training set size: 455 samples
Testing set size: 114 samples

--- Logistic Regression ---
Logistic Regression is a linear model used for binary classification. It models the probability that a given input belongs to a certain class by applying a logistic (sigmoid) function to a linear combination of the features. The output is a probability, which is then thresholded to make a class prediction. It's suitable for this dataset because breast cancer classification is a binary outcome (malignant or benign), and the relationships between features and the target can often be well-approximated linearly in a transformed space, especially after scaling, which it benefits from.

Logistic Regression model training complete.

Model Evaluation on Test Data (Logistic Regression):
Accuracy: 0.9737
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy       

Decision Tree Classifier

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

print("\n--- Decision Tree Classifier ---")
print("A Decision Tree Classifier is a non-parametric supervised learning method used for classification. It works by creating a tree-like model of decisions, where each internal node represents a 'test' on an attribute, each branch represents the outcome of the test, and each leaf node represents a class label (the decision). It's suitable for this dataset because it can capture non-linear relationships and interactions between features without requiring feature scaling, though it can still perform well with scaled data. Its interpretability can also be a benefit for understanding feature importance in classifying breast cancer.")

model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(X_train, y_train)

print("\nDecision Tree Classifier model training complete.")

y_pred_dt = model_dt.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred_dt)
report_dt = classification_report(y_test, y_pred_dt)

print(f"\nModel Evaluation on Test Data (Decision Tree Classifier):")
print(f"Accuracy: {accuracy_dt:.4f}")
print("Classification Report:")
print(report_dt)

Training set size: 455 samples
Testing set size: 114 samples

--- Decision Tree Classifier ---
A Decision Tree Classifier is a non-parametric supervised learning method used for classification. It works by creating a tree-like model of decisions, where each internal node represents a 'test' on an attribute, each branch represents the outcome of the test, and each leaf node represents a class label (the decision). It's suitable for this dataset because it can capture non-linear relationships and interactions between features without requiring feature scaling, though it can still perform well with scaled data. Its interpretability can also be a benefit for understanding feature importance in classifying breast cancer.

Decision Tree Classifier model training complete.

Model Evaluation on Test Data (Decision Tree Classifier):
Accuracy: 0.9474
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        43
           1   

Random Forest Classifier

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

print("\n--- Random Forest Classifier ---")
print("A Random Forest Classifier is an ensemble learning method that operates by constructing a multitude of decision trees during training and outputting the class that is the mode of the classes (classification) of the individual trees. It's suitable for this dataset because it can handle high-dimensional data, is robust to overfitting (more so than a single Decision Tree), and can capture complex non-linear relationships. It generally provides higher accuracy than single decision trees and handles feature interactions well.")

model_rf = RandomForestClassifier(random_state=42)
model_rf.fit(X_train, y_train)

print("\nRandom Forest Classifier model training complete.")

y_pred_rf = model_rf.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_rf)
report_rf = classification_report(y_test, y_pred_rf)

print(f"\nModel Evaluation on Test Data (Random Forest Classifier):")
print(f"Accuracy: {accuracy_rf:.4f}")
print("Classification Report:")
print(report_rf)

Training set size: 455 samples
Testing set size: 114 samples

--- Random Forest Classifier ---
A Random Forest Classifier is an ensemble learning method that operates by constructing a multitude of decision trees during training and outputting the class that is the mode of the classes (classification) of the individual trees. It's suitable for this dataset because it can handle high-dimensional data, is robust to overfitting (more so than a single Decision Tree), and can capture complex non-linear relationships. It generally provides higher accuracy than single decision trees and handles feature interactions well.

Random Forest Classifier model training complete.

Model Evaluation on Test Data (Random Forest Classifier):
Accuracy: 0.9649
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      0.97        71

    accuracy                           0.96       114
   macro a

Support Vector Machine (SVM)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

print("\n--- Support Vector Machine (SVM) ---")
print("Support Vector Machines (SVMs) are powerful and versatile machine learning models capable of performing linear or non-linear classification, regression, and even outlier detection. For classification, SVMs work by finding the optimal hyperplane that best separates the classes in the feature space. It's suitable for this dataset because it performs well on high-dimensional data and can effectively handle cases where the classes are not linearly separable by using kernel tricks. It is sensitive to feature scaling, which has already been performed.")

model_svm = SVC(random_state=42)
model_svm.fit(X_train, y_train)

print("\nSupport Vector Machine (SVM) model training complete.")

y_pred_svm = model_svm.predict(X_test)

accuracy_svm = accuracy_score(y_test, y_pred_svm)
report_svm = classification_report(y_test, y_pred_svm)

print(f"\nModel Evaluation on Test Data (Support Vector Machine (SVM)):")
print(f"Accuracy: {accuracy_svm:.4f}")
print("Classification Report:")
print(report_svm)

Training set size: 455 samples
Testing set size: 114 samples

--- Support Vector Machine (SVM) ---
Support Vector Machines (SVMs) are powerful and versatile machine learning models capable of performing linear or non-linear classification, regression, and even outlier detection. For classification, SVMs work by finding the optimal hyperplane that best separates the classes in the feature space. It's suitable for this dataset because it performs well on high-dimensional data and can effectively handle cases where the classes are not linearly separable by using kernel tricks. It is sensitive to feature scaling, which has already been performed.

Support Vector Machine (SVM) model training complete.

Model Evaluation on Test Data (Support Vector Machine (SVM)):
Accuracy: 0.9737
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy               

k-Nearest Neighbors (k-NN)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

print("\n--- k-Nearest Neighbors (k-NN) ---")
print("k-Nearest Neighbors (k-NN) is a non-parametric, lazy learning algorithm used for both classification and regression. In classification, the output is a class membership. An object is classified by a majority vote of its neighbors, with the object being assigned to the class most common among its k nearest neighbors (k is a positive integer, typically small). It's suitable for this dataset because it's effective for non-linear decision boundaries and works well when the data is well-separated into classes. It's also a distance-based algorithm, so it benefits greatly from feature scaling, which has already been performed.")

model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train, y_train)

print("\nk-Nearest Neighbors (k-NN) model training complete.")

y_pred_knn = model_knn.predict(X_test)

accuracy_knn = accuracy_score(y_test, y_pred_knn)
report_knn = classification_report(y_test, y_pred_knn)

print(f"\nModel Evaluation on Test Data (k-Nearest Neighbors (k-NN)):")
print(f"Accuracy: {accuracy_knn:.4f}")
print("Classification Report:")
print(report_knn)

Training set size: 455 samples
Testing set size: 114 samples

--- k-Nearest Neighbors (k-NN) ---
k-Nearest Neighbors (k-NN) is a non-parametric, lazy learning algorithm used for both classification and regression. In classification, the output is a class membership. An object is classified by a majority vote of its neighbors, with the object being assigned to the class most common among its k nearest neighbors (k is a positive integer, typically small). It's suitable for this dataset because it's effective for non-linear decision boundaries and works well when the data is well-separated into classes. It's also a distance-based algorithm, so it benefits greatly from feature scaling, which has already been performed.

k-Nearest Neighbors (k-NN) model training complete.

Model Evaluation on Test Data (k-Nearest Neighbors (k-NN)):
Accuracy: 0.9474
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        43
           1

For each algorithm, provide a brief description of how it works and why it might be suitable for this dataset.
Model Comparison (2 marks):

 ● Compare the performance of the five classification algorithms.

 ● Which algorithm performed the best and which one performed the worst?


--- Model Comparison ---

Accuracy of each algorithm on the test set:

Logistic Regression             0.973684

Support Vector Machine (SVM)    0.973684

Random Forest Classifier        0.964912

Decision Tree Classifier        0.947368

k-Nearest Neighbors (k-NN)      0.947368
dtype: float64

Best performing algorithm: Logistic Regression (Accuracy: 0.9737)

Worst performing algorithm: Decision Tree Classifier (Accuracy: 0.9474)

In [ ]:
import pandas as pd

print("\n--- Model Comparison ---")

model_accuracies = {
    "Logistic Regression": accuracy_lr,
    "Decision Tree Classifier": accuracy_dt,
    "Random Forest Classifier": accuracy_rf,
    "Support Vector Machine (SVM)": accuracy_svm,
    "k-Nearest Neighbors (k-NN)": accuracy_knn
}

accuracies_series = pd.Series(model_accuracies)

print("\nAccuracy of each algorithm on the test set:")
print(accuracies_series.sort_values(ascending=False))

best_algorithm = accuracies_series.idxmax()
worst_algorithm = accuracies_series.idxmin()

print(f"\nBest performing algorithm: {best_algorithm} (Accuracy: {accuracies_series.max():.4f})")
print(f"Worst performing algorithm: {worst_algorithm} (Accuracy: {accuracies_series.min():.4f})")

print("\n--- Justification and Discussion ---")
print("To provide a comprehensive comparison, we can analyze not only accuracy but also other metrics from the classification reports (precision, recall, F1-score) for a deeper insight into each model's performance on both classes (malignant vs. benign).")
print("\n- **Logistic Regression** and **SVM** often perform well on datasets where a clear decision boundary exists or can be effectively mapped to a higher dimension via kernels. Their strong performance here suggests the features, after scaling, allow for good separation.")
print("- **Random Forest**, an ensemble method, generally provides robust performance by mitigating overfitting that can occur with single decision trees. Its slightly lower accuracy than LR/SVM here could be due to the specific dataset characteristics or default hyperparameters.")
print("- **Decision Tree** and **k-NN** tend to be more susceptible to noise or complex feature interactions if not carefully tuned. k-NN's performance is highly dependent on the choice of 'k' and the distance metric, while Decision Trees can easily overfit. Their similar accuracies might indicate similar limitations or optimal performance within the default settings for this dataset.")
print("\nIn this assessment, the Logistic Regression and Support Vector Machine algorithms performed the best, both achieving an accuracy of 0.9737. The Decision Tree Classifier and k-Nearest Neighbors (k-NN) performed the worst, both with an accuracy of 0.9474. The Random Forest Classifier was in between with an accuracy of 0.9649.")
print("The dataset appears to be relatively clean and the features are well-suited for linear and semi-linear models, especially after feature scaling. The models that performed best are those that are good at finding optimal separation boundaries in the feature space.")


--- Model Comparison ---

Accuracy of each algorithm on the test set:
Logistic Regression             0.973684
Support Vector Machine (SVM)    0.973684
Random Forest Classifier        0.964912
Decision Tree Classifier        0.947368
k-Nearest Neighbors (k-NN)      0.947368
dtype: float64

Best performing algorithm: Logistic Regression (Accuracy: 0.9737)
Worst performing algorithm: Decision Tree Classifier (Accuracy: 0.9474)

--- Justification and Discussion ---
To provide a comprehensive comparison, we can analyze not only accuracy but also other metrics from the classification reports (precision, recall, F1-score) for a deeper insight into each model's performance on both classes (malignant vs. benign).

- **Logistic Regression** and **SVM** often perform well on datasets where a clear decision boundary exists or can be effectively mapped to a higher dimension via kernels. Their strong performance here suggests the features, after scaling, allow for good separation.
- **Random Fores

Timely Submission (1 mark)

● Submission Guidelines: Provide your code in a Jupyter Notebook format and submit the GitHub link here. Ensure your explanations and answers are clear and concise.
Total Score: 10